# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f73ce9658f82db42cd740949937366e4bc0ff45fff056d4da8035f518f242403bcb30fda356a2cb4f90365f8b3a2c089ab1bc96307ea03be481a837f166b42ae

test:
  secret_key_base: 4bbf8a5ce38229494147b14753f819018bd2dc0b1fa45b6507ac73cde87a9b25bfff3925070e066da0db3da11ad20f9f8069a52c3f27f00c17c956d13aeaabbc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
